# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'liberica'
      - name: Check with Kotlin 1.4.20
        run: |
          ./gradlew -Pkotlin_version=1.4.20 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
      - name: Check with Kotlin 1.4.30
        run: |
          ./gradlew -Pkotlin_version=1.4.30 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
      - name: Check with Kotlin 1.5.0
        run: |
          ./gradlew -Pkotlin_version=1.5.0 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
      - name: Check with Kotlin 1.5.10
        run: |
          ./gradlew -Pkotlin_version=1.5.10 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
      - name: Check with Kotlin 1.5.20
        run: |
          ./gradlew -Pkotlin_version=1.5.20 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
      - name: Check with Kotlin 1.5.30
        run: |
          ./gradlew -Pkotlin_version=1.5.30 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
      - name: Check with Kotlin 1.6.0
        run: |
          ./gradlew -Pkotlin_version=1.6.0 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
      - name: Check with Kotlin 1.7.0
        run: |
          ./gradlew -Pkotlin_version=1.7.0 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
      - name: Check with Kotlin 1.8.0
        run: |
          ./gradlew -Pkotlin_version=1.8.0 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
      - name: Check with Kotlin 1.9.0
        run: |
          ./gradlew -Pkotlin_version=1.9.0 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
      - name: Check with Kotlin 1.9.20
        run: |
          ./gradlew -Pkotlin_version=1.9.20 clean linkDebugTestMacosX64
          ./build/bin/macosX64/debugTest/test.kexe
